// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9bAbAFmQyBEIO8BpB3th18834TL2RKvk',
    appId: '1:699346646474:web:91e9ffb8dff85bafe60b33',
    messagingSenderId: '699346646474',
    projectId: 'route-studio',
    authDomain: 'route-studio.firebaseapp.com',
    storageBucket: 'route-studio.firebasestorage.app',
    measurementId: 'G-GM8WCGZZ9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV3VsD_GnSqK-6R-gVJ9rHU6IfeFYCeo8',
    appId: '1:699346646474:android:ef43f7d73a4f54d0e60b33',
    messagingSenderId: '699346646474',
    projectId: 'route-studio',
    storageBucket: 'route-studio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE5y1-uVxacEjaFrrnIPm-CMxlZ2IEIUA',
    appId: '1:699346646474:ios:156f977d77923845e60b33',
    messagingSenderId: '699346646474',
    projectId: 'route-studio',
    storageBucket: 'route-studio.firebasestorage.app',
    iosClientId: '699346646474-envcs0ig5d2ogo2sti5adssko1iok8qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.routeGenApp',
  );

}